---
apiVersion: v1
kind: ReplicationController
metadata: 
  labels:
    name: helloworld
  name: helloworld-controller
spec:
  replicas: 1
  template:
    metadata: 
      labels:
        name: helloworld
    spec:
      containers:
      - image: raja6522/helloworld
        name: helloworldapp
        ports:
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld
  name: helloworld
spec:
  selector:
    name: helloworld
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
