---
apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworldapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - image: raja6522/helloworld
        name: helloworldcontainer
        ports:
          containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld
  name: helloworldservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: helloworld
