---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 30 
  selector:
    matchLabels:
      name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - image: raja6522/helloworld
        name: helloworldcontainer
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld
  name: helloworldservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: helloworld
